export App from './App/App';
export Chat from './Chat/Chat';
export Home from './Home/Home';
// export Widgets from './Widgets/Widgets';
export About from './About/About';
export Login from './Login/Login';
export LoginSuccess from './LoginSuccess/LoginSuccess';
// export Survey from './Survey/Survey';
export NotFound from './NotFound/NotFound';
// export Pagination from './Pagination/Pagination';
// export AssetsManager from './AssetsManager/AssetsManager';
// export AssetsList from './AssetsManager/AssetsList';
// export AssetsCreate from './AssetsManager/AssetsCreate';
// export AssetsCreate1 from './AssetsManager/AssetsCreate1';
// export AssetsCreate2 from './AssetsManager/AssetsCreate2';
// export AssetsCreate3 from './AssetsManager/AssetsCreate3';
export MainPage from './MainPage/MainPage';
// export Deposit from './Deposit/Deposit';
// export OAssets from './OAssets/OAssets';
// export Withdraw from './Withdraw/Withdraw';
// export TMarket from './TMarket/TMarket';
// export TRecords from './TRecords/TRecords';
export ExistEvidents from './ExistEvidents/ExistEvidents';
export Signup from './Signup/Signup';
export OAssetTransfer from './OAssets/OAssetTransfer';
export LocalFile from './ExistEvidents/localfile/localfile';
export RemoteFile from './ExistEvidents/remotefile/remotefile';
export UploadFile from './ExistEvidents/uploadfile/uploadfile';
export TextInfo from './ExistEvidents/textinfo/textinfo';
export Proof from './ExistEvidents/proof/proof';
// export LocalFile1 from './ExistEvidents/localfile/localfile1';
